openapi: 3.0.1
info:
  title: API CANES
  description: Documentaci√≥n del proyecto final
  version: 1.0.0

paths:
  /api/users:
    get:
      summary: Obtener usuarios
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuarios

  /api/pets:
    get:
      summary: Obtener mascotas
      tags:
        - Pets
      responses:
        "200":
          description: Lista de mascotas

  /api/adoptions:
    get:
      summary: Obtener adopciones
      tags:
        - Adoptions
      responses:
        "200":
          description: Lista de adopciones